### PR TITLE
Add optional timezone offset for NTP.set_time()

### PR DESCRIPTION
**Pull request by theelectricmayhem**
Updated `NTP.set_time()` to accept an optional `tz_offset` which adjusts the recorded time by that number of hours.

### CODE REVIEW

**Comment by theelectricmayhem** [comment]
Thanks!  Hopefully Black cleaned up that formatting issue.  Is there a particular target version of python used for Adafruit libraries I should be using with Black?

**Comment by brentru** [comment]
Seems like 3.5? Via the Action:
> Run black --check --target-version=py35 .

**Comment by theelectricmayhem** [comment]
> Seems like 3.5? Via the Action:
> 
> > Run black --check --target-version=py35 .

Sweet.  Thanks

**Comment by theelectricmayhem** [comment]
That's absolutely the right way to do it.  Thanks!  New PR

**Comment by jepler** [comment]
Aha I didn't see that the PR had already been merged.  Looking forward to the next one and thanks @theelectricmayhem !

**Pull request merged**
