### PR TITLE
Use UDP to talk to NTP servers

### LINKED ISSUE #16: Dependence on adafruit_esp32spi
It seems this library only works with adafruit_esp32spi.
What can be done to make it compatible with other backends such as adafruit_wiznet5k?

The current implementation calls `get_time` on on the interface object.  So is the right way to implement this to add this method to the adafruit_wiznet5k interface object?  Or should this module be rewritten to use generic socket calls?

### LINKED ISSUE #17: tz_offset is incorrectly documented in the code and documentation
The code describes the tz_offset code as:
        :param int tz_offset: The offset of the local timezone,
            in seconds west of UTC (negative in most of Western Europe,
            positive in the US, zero in the UK).
        """

        try:
            now = self._esp.get_time()
            now = time.localtime(now[0] + tz_offset)

Timezone offset in the US is negative. For example MST7 is -25200.

### PR DESCRIPTION
**Pull request by tannewt**
This completely redoes the library in favor of using a native
socket to fetch time from an NTP server.

Fixes #17 and fixes #16

### CODE REVIEW

**Review by ladyada — CHANGES_REQUESTED** [review]
looks good - since the readme example was deleted, can you add an example for using with esp32spi?

**Comment by tannewt** [comment]
I'm not sure it works with ESP32SPI. `get_time()` on ESP32SPI already gets the time from NTP I believe.

**Review by ladyada — APPROVED** [review]
gtg!

**Comment by mattura** [comment]
Any chance you could add a socket timeout? My code frequently hangs during the ntp call (eg if the connection is lost), but passing a timeout can resolve this, ie. put a socket_timeout as an additional argument and then call sock.settimeout(self._socket_timeout) before the sock.sendto
Cheers

**Pull request merged**
